version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tododb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    container_name: todo-api-redis
    restart: always
    command: redis-server --requirepass mysecretpassword

  minio:
    container_name: todo-api-minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: nktkln
      MINIO_ROOT_PASSWORD: mysecretpassword
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
      - minio

volumes:
  minio-storage:
  postgres-data:
