version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tododb
    volumes:
      - ./.databases/postgres/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: todo-api-redis
    restart: always
    command: redis-server --requirepass mysecretpassword

  minio:
    image: minio/minio:latest
    container_name: todo-api-minio
    restart: always
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./.databases/minio/data:/data

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    command: sh -c "/wait && ./app"
    environment:
      WAIT_HOSTS: postgres:5432,redis:6379,minio:9000
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
      - minio
